sudo: required
language: go
go:
  - "1.5"
services:
  - docker
env:
  global:
    - DOCKER_EMAIL=jvehent@mozilla.com
    - DOCKER_USERNAME=jvehent
    - secure: "LwcQZ/M+4M+HJf6b/bKcGdmuTcT4XeN5MVuBSy34ag79/Zz3UinwBpW3peOhFNizJUbMVzPJJ7FGMWeUouq6lCcjjQZAIBnPWx/bhP0z7vIO8t2+XqKV47D3HqPOokqEdeKHvzr4xvfKGMBy+VMCWeuFI7Z3BLCqtWSQYDjAMTg="
    - TAG=$(date +%Y%m%d%H%M)
before_deploy:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
before_install:
    - sudo docker build -t tls-observatory:$TAG .
    - sudo docker push jvehent/tls-observatory

#deploy:
#  provider: elasticbeanstalk
#  on:
#      repo: mozilla/tls-observatory
#      branch: master
#  skip_cleanup: true
#  zip-file: build/eb-app-latest.zip
#  app: tls-observatory-ulfr
#  env: tls-observatory-dev
#  region: us-east-1
#  bucket_name: elasticbeanstalk-us-east-1-1234567890
#  bucket_path: tls-observatory-ulfr/
#  access-key-id:
#    secure: "itEK2FdnjTKwc664GVKSekV3bwHxT2BR3PHg6eVp58rtdok/tlhOQC9FxYuby7CrG8fjW0M+zd1zX7rjNQQ8vcaRkfKAJEibP9RxhfLDOUkkW6ujl94nCrsDZ9F/C0na38g77oCAYMFVqpa/cVcuROzb5NRGUzNnavA+Iq6erlMx9RJvmBtEpTjki03xXZEK1zQb1u9+SBM1288LF6oIZKSNXpEtIweMWg6PKBR8JRqpJBoLVaVYqFJe4hvHl37CahDrNKSBPA0ovtquzWf40LMBCZjsZXmqSfsVcPSHPzYC9qzabS92b/uxR/RtJYs/Odh2SJ8dBk74EhM8NhQfpQwNavWRsvzdGJoH//SbWSQKvzakacq9cbFFEIoJoQ/OiPwX/lsADJuWjera7zeBqvHdTc57uAmE1DqqDPu2Ff/QY69b6Tr+xT/ckrF+SNHN/I+XEmSrjMrb4/iMKtomtu7xKH5oZl+eW4QTVLZpnBVhez75srt9K7+eCjOZq+NzUMoN8seqxxvP2peQodkvN9v09ROAOe0ybfuzZBl9TPA35OIzl4oJjBatibbbbcfFjX5h4bEsyYGsbfWFZSlOHnwtcuMouasRuBgZP06CMwmBmkQeN4l+HNXFi4KvrlUz4ZJKoAelncEXlI2Lr9dVrcVx5gWr5cS3sMM1KyDJZ3c="
#  secret-access-key:
#    secure: "n/+6zYg21oGjuMewrJO/NRvMEOlAAPkNzJH6CYR0ezV7sOhBMag8wmX6VvCzCKJLEQaW3PZvH98euEylqlXxzH0PlWelbAChq1gCKvj38g5vfiV+4DriOJhd4JzNkWsVa57u+8Z5rKmBdQQN9m/9gYANC759g5eQShxVR3VNMoAW7Ueq9THj8FBrAwRKWnNRGhKK2FavCpy3003hLWaHmo50HNOG7zT+6x4lL9awsRH40X9LuPiWuBNYQ3RLxdt43EVao6mheYdAZLe6wdJEtTY1QRq1NoYpld89h73QE3lJRIb12AhtMLZv+jq09GGdruE3Y2LbogLvuLFd9uwzwaIstDqUxKZPLxG5Pgf+6c5yk1w+zBafjhXYK3gkQe4JEujKIieB2ZN6qg2RkdJb4+yudJwzNzPYPE0eN90i4aT+Yy7ZxN36SoT5bJmWZ4V1nEJB1vmpaHYy0hdQ4/70tT73RFLYg/VZgZqJekbZTGysqeNDSBYEWmkf2kNiENZt9M+a7Lr0RysPCPSVK+ckJpeGSBzHxbYv/xQhi5tV82blEerW0ws/qoxrrvFgdT8iujs+csaVQ0P4/NsQyasAUkimKyoQTyPRUakgKciw5P0zKfYUMjOs34EblbR0E8iJqC4Mc29lCUCIMLld0cNjPzfd7alHMx3pUPoH3VlIFxU="

